server.port=8081
spring.main.banner-mode=off

#DB settings
spring.datasource.url=jdbc:postgresql://localhost:5433/JavaFSDFinanceMVC_2.0
spring.datasource.username=postgres
spring.datasource.password=#Zlrx4321
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update  
#The above property ensures that if we dont have a table then hibernate will create one
spring.jpa.show-sql=true
#If you want to see what query is being fired then the above line is needed